### ISSUE TITLE
Could not get logs from hailataxii.com

### ISSUE THREAD

**Issue by mesarvagya** [CiscoCTA/taxii-log-adapter#1]
I have tried to consume the stix documents from _hailataxii.com_. I tried both _stix2cef.xml_ and _stix2splunk.xml_ for the feed _guest.Abuse_ch_. Both of these stylesheet cannot transform the poll response. Am I doing something wrong or taxii-log-adapter cannot parse poll response from hailataxii.com. Some of the samples include below:
[guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_105318_00_00.txt](https://github.com/CiscoCTA/taxii-log-adapter/files/302191/guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_105318_00_00.txt)
[guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_109764_00_00.txt](https://github.com/CiscoCTA/taxii-log-adapter/files/302192/guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_109764_00_00.txt)
[guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_107730_00_00.txt](https://github.com/CiscoCTA/taxii-log-adapter/files/302193/guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_107730_00_00.txt)
[guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_105318_00_00.txt](https://github.com/CiscoCTA/taxii-log-adapter/files/302185/guest.Abuse_ch_STIX111_t2016_06_01T06_16_41_105318_00_00.txt)

**Comment by dvoraktomas** [comment]
The existing stylesheets support only STIX-incidents, specifically incidents produced by https://cognitive.cisco.com/
(I will update the wiki to make this clear.)

The feeds mentioned above contain STIX-indicators, you would need to write a stylesheet for such transformation.
The existing incident stylesheets (e.g. https://github.com/CiscoCTA/taxii-log-adapter/blob/master/src/main/resources/config/template/stix2splunk.xsl) contain

    <xsl:template match="s:STIX_Package">
        <xsl:apply-templates select="s:Incidents">
            <xsl:with-param name="customer" select="s:STIX_Header/s:Information_Source/sc:Identity/@id"/>
        </xsl:apply-templates>
    </xsl:template>

    <xsl:template match="s:Incident">
        <xsl:param name="customer"/>
        ... transformation from the STIX incident is here
    </xsl:template>

Instead you would need something like the following code

    <xsl:template match="s:STIX_Package">
        <xsl:apply-templates select="s:Indicators"/>
    </xsl:template>

    <xsl:template match="s:Indicator">
        ... transformation from the STIX indicator is here
    </xsl:template>
